# Generated by Django 5.2.5 on 2025-08-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("unique_gene_ids", models.JSONField()),
                ("chromosome", models.CharField(max_length=10)),
                ("start", models.IntegerField()),
                ("end", models.IntegerField()),
                ("primer_based_count", models.IntegerField()),
                ("percentage", models.FloatField()),
                ("minimum_count", models.IntegerField()),
                ("maximum_count", models.IntegerField()),
                ("forward_count", models.IntegerField()),
                ("reverse_count", models.IntegerField()),
                ("meandepth", models.FloatField()),
                ("stdev", models.FloatField(null=True)),
            ],
        ),
    ]
